<a href="https://colab.research.google.com/github/Rifal737/Pemrograman-web/blob/main/Copy_of_P1_Big_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Big Data dengan Dataset Saham Antam**

**Nama & NIM :**  

**1. Arsya Pramudya Kuntadi (24.11.6078)  
2. Muhamad Rifal (24.11.6082)**    
  
  
**Kelas : IF 03**

**1. Menambah Library**

In [ ]:
#import Library
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib as mpl
import matplotlib.pyplot as plt

**2. Mengupload File**

**dari link gitthub/website**

**a. Dari Lokal Komputer**

In [ ]:
from google.colab import files
upload = files.upload()

Saving ANTM.JK.csv to ANTM.JK.csv

**b. Dari link google collab**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Big Data/ANTM.JK.csv')
df.head(10)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Date,Open,High,Low,Close,Adj Close,Volume
0,2005-09-29,432.588074,436.787964,407.388763,432.588074,304.904572,76180670.0
1,2005-09-30,457.787384,457.787384,432.588074,457.787384,322.666016,105493978.0
2,2005-10-03,470.387024,474.586914,440.987854,470.387024,331.546692,59712955.0
3,2005-10-04,474.586914,482.986694,466.187164,474.586914,334.506927,56236668.0
4,2005-10-05,482.986694,482.986694,466.187164,482.986694,340.427429,31319315.0
5,2005-10-06,466.187164,482.986694,461.987274,466.187164,328.586487,8107366.0
6,2005-10-07,470.387024,470.387024,457.787384,470.387024,331.546692,6577562.0
7,2005-10-10,466.187164,470.387024,457.787384,466.187164,328.586487,23223854.0
8,2005-10-11,466.187164,466.187164,461.987274,466.187164,328.586487,13497395.0
9,2005-10-12,470.387024,474.586914,466.187164,470.387024,331.546692,29804392.0

**c. Dari API Kaggle**

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"arsyapramudya","key":"e22eeddf6d716a014ddd6d5f96604e04"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d muhardianabasandi/antam-stock-market-by-kitto

Dataset URL: https://www.kaggle.com/datasets/muhardianabasandi/antam-stock-market-by-kitto
License(s): CC0-1.0
Downloading antam-stock-market-by-kitto.zip to /content
100% 62.8k/62.8k [00:00<00:00, 334kB/s]

Karena masih dalam bentuk Zip kita unzip dulu

In [ ]:
!unzip antam-stock-market-by-kitto.zip

Archive:  antam-stock-market-by-kitto.zip
replace ANTM.JK.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: antam_stock_market.csv
replace antam_stock_market.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: antam_stock_market.csv

In [ ]:
df = pd.read_csv('antam_stock_market.csv')
df.head(5)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2005-09-29,432.588074,436.787964,407.388763,432.588074,304.904572,76180670.0
1,2005-09-30,457.787384,457.787384,432.588074,457.787384,322.666016,105493978.0
2,2005-10-03,470.387024,474.586914,440.987854,470.387024,331.546692,59712955.0
3,2005-10-04,474.586914,482.986694,466.187164,474.586914,334.506927,56236668.0
4,2005-10-05,482.986694,482.986694,466.187164,482.986694,340.427429,31319315.0

**d. Dari link Github/website**

**3. Menampilkan Dataset**

In [ ]:
#membaca file dataset csv
df=pd.read_csv("ANTM.JK.csv",encoding='latin1')
#menampilkan 10 data teratas
df.head(20)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2005-09-29,432.588074,436.787964,407.388763,432.588074,304.904572,76180670.0
1,2005-09-30,457.787384,457.787384,432.588074,457.787384,322.666016,105493978.0
2,2005-10-03,470.387024,474.586914,440.987854,470.387024,331.546692,59712955.0
3,2005-10-04,474.586914,482.986694,466.187164,474.586914,334.506927,56236668.0
4,2005-10-05,482.986694,482.986694,466.187164,482.986694,340.427429,31319315.0
5,2005-10-06,466.187164,482.986694,461.987274,466.187164,328.586487,8107366.0
6,2005-10-07,470.387024,470.387024,457.787384,470.387024,331.546692,6577562.0
7,2005-10-10,466.187164,470.387024,457.787384,466.187164,328.586487,23223854.0
8,2005-10-11,466.187164,466.187164,461.987274,466.187164,328.586487,13497395.0
9,2005-10-12,470.387024,474.586914,466.187164,470.387024,331.546692,29804392.0
10,2005-10-13,474.586914,474.586914,470.387024,474.586914,334.506927,12738446.0
11,2005-10-14,474.586914,474.586914,470.387024,474.586914,334.506927,12018188.0
12,2005-10-17,474.586914,474.586914,474.586914,474.586914,334.506927,0.0
13,2005-10-18,470.387024,474.586914,470.387024,470.387024,331.546692,12110452.0
14,2005-10-19,461.987274,470.387024,461.987274,461.987274,325.626251,5631107.0
15,2005-10-20,461.987274,461.987274,461.987274,461.987274,325.626251,0.0
16,2005-10-21,461.987274,461.987274,461.987274,461.987274,325.626251,3038774.0
17,2005-10-24,449.387604,461.987274,445.187744,449.387604,316.745544,10875299.0
18,2005-10-25,449.387604,449.387604,449.387604,449.387604,316.745544,0.0
19,2005-10-26,453.587494,457.787384,449.387604,453.587494,319.705750,14298013.0

**4. Menampilkan Struktur Dataset**

In [ ]:
#Melihat struktur Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3808 entries, 0 to 3807
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3808 non-null   object
 1   Open       3807 non-null   float64
 2   High       3807 non-null   float64
 3   Low        3807 non-null   float64
 4   Close      3807 non-null   float64
 5   Adj Close  3807 non-null   float64
 6   Volume     3807 non-null   float64
dtypes: float64(6), object(1)
memory usage: 208.4+ KB

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [ ]:
df.shape

(3808, 7)